### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#23]
Not all providers have minzoom / maxzoom--some defaults should be used.

```
Stacktrace (most recent call first):

  atlas.rb:253:in `calculate_zoom'
    [info[:minzoom], z, info[:maxzoom]].sort[1]
  atlas.rb:316:in `pick_zoom'
    self.zoom = calculate_zoom(west, east)
 ...
```

https://app.getsentry.com/stamen/field-papers/group/59324776/

**Comment by mojodna** [comment]
Partially fixed by @sconnelley in https://github.com/fieldpapers/fp-web/commit/96853f74455663f4e510d6798fcac7be19abd17a
