### ISSUE TITLE
Replace Open3 with IO.popen

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#66]
https://app.getsentry.com/stamen/field-papers/group/64418934/

```
NoMethodError: undefined method `pid' for nil:NilClass
  generate_pdf_job.rb:151:in `rescue in render_page'
    Process.kill(9, status.pid)
  generate_pdf_job.rb:144:in `render_page'
    begin
  generate_pdf_job.rb:28:in `perform'
    files = atlas.pages.map(&method(:render_page))
...
(43 additional frame(s) were not displayed)
```

`status` doesn't get set if `Open3.capture3` times out.

http://coldattic.info/shvedsky/pro/blogs/a-foo-walks-into-a-bar/posts/63 looks useful.

**Comment by mojodna** [comment]
Ugh: https://gist.github.com/lpar/1032297

**Comment by mojodna** [comment]
Looks like the answer is to go back to not using `Open3` (which I introduced for snapshot processing in order to more effectively pipe image data into a process as stdin and get the result as stdout).

**Comment by mojodna** [comment]
Fixed in https://github.com/fieldpapers/fp-web/commit/78b47da661c049ef976744f6847386253d06261e
