### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#79]
https://app.getsentry.com/stamen/field-papers/group/64738205/

```
NoMethodError: undefined method `[]' for nil:NilClass
  placefinder.rb:19:in `query'
    result = rsp.body["query"]["results"]["Result"]
  compose_controller.rb:26:in `show'
    zoom, longitude, latitude = Placefinder.query(params[:q])
...
(76 additional frame(s) were not displayed)
```

Query was `q=Br%C3%BCgelplatte`

**Comment by mojodna** [comment]
Fixed in fieldpapers/fp-web@7750c63882e077ecac65860825d65512e3ea9f07
